### Send POST request with json body
POST http://localhost:3000/journal/entries
Content-Type: application/json

{
  "createdAt": "2023-09-24T23:48:52.000Z",
  "createdAtShowsTime": false,
  "parent": null,
  "topic": "prueba prueba",
  "status": null,
  "closedAt": null,
  "closedAtShowsTime": false
}

###
PUT http://localhost:3000/journal/entries/1
Content-Type: application/json

{
  "createdAt": "2023-09-25T16:26:06.000Z",
  "createdAtShowsTime": true,
  "parent": null,
  "topic": "topic topic 2c",
  "status": null,
  "closedAt": null,
  "closedAtShowsTime": true
}

###
GET http://localhost:3000/journal/entries/1

###
DELETE http://localhost:3000/journal/entries/1